<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="54" started-at="2022-06-26T20:23:41 EDT" finished-at="2022-06-26T20:23:41 EDT">
    <groups>
    </groups>
    <test name="suiteA" duration-ms="54" started-at="2022-06-26T20:23:41 EDT" finished-at="2022-06-26T20:23:41 EDT">
      <class name="SuiteA.PracticeDataProvider">
        <test-method status="FAIL" signature="useDataProvider(java.lang.String, java.lang.String, java.lang.String, int)[pri:0, instance:SuiteA.PracticeDataProvider@396f6598]" name="useDataProvider" duration-ms="8" started-at="2022-06-26T20:23:41 EDT" data-provider="DPMethod" finished-at="2022-06-26T20:23:41 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[Harman]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Toronto]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Canada]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1500]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Testcase is failing here]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Testcase is failing here
at org.testng.Assert.fail(Assert.java:97)
at SuiteA.PracticeDataProvider.useDataProvider(PracticeDataProvider.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- useDataProvider -->
        <test-method status="FAIL" signature="useDataProvider(java.lang.String, java.lang.String, java.lang.String, int)[pri:0, instance:SuiteA.PracticeDataProvider@396f6598]" name="useDataProvider" duration-ms="1" started-at="2022-06-26T20:23:41 EDT" data-provider="DPMethod" finished-at="2022-06-26T20:23:41 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[Haris]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Missisuaga]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Canada]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[2000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Testcase is failing here]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Testcase is failing here
at org.testng.Assert.fail(Assert.java:97)
at SuiteA.PracticeDataProvider.useDataProvider(PracticeDataProvider.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- useDataProvider -->
        <test-method status="FAIL" signature="useDataProvider(java.lang.String, java.lang.String, java.lang.String, int)[pri:0, instance:SuiteA.PracticeDataProvider@396f6598]" name="useDataProvider" duration-ms="1" started-at="2022-06-26T20:23:41 EDT" data-provider="DPMethod" finished-at="2022-06-26T20:23:41 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[SatyaPriya]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Delhi]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[India]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[3000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Testcase is failing here]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Testcase is failing here
at org.testng.Assert.fail(Assert.java:97)
at SuiteA.PracticeDataProvider.useDataProvider(PracticeDataProvider.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- useDataProvider -->
        <test-method status="PASS" signature="InstDataProvider(java.lang.String, java.lang.String, int)[pri:1, instance:SuiteA.PracticeDataProvider@396f6598]" name="InstDataProvider" duration-ms="1" started-at="2022-06-26T20:23:41 EDT" data-provider="DPMethod" finished-at="2022-06-26T20:23:41 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[Mitesh]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[m@abc.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[10000]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InstDataProvider -->
        <test-method status="PASS" signature="InstDataProvider(java.lang.String, java.lang.String, int)[pri:1, instance:SuiteA.PracticeDataProvider@396f6598]" name="InstDataProvider" duration-ms="1" started-at="2022-06-26T20:23:41 EDT" data-provider="DPMethod" finished-at="2022-06-26T20:23:41 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[Dilip]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[d@abc.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[15000]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InstDataProvider -->
      </class> <!-- SuiteA.PracticeDataProvider -->
    </test> <!-- suiteA -->
  </suite> <!-- Suite -->
</testng-results>
